[package]
name = "vad"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ndarray = "0.16.1"
ort = { version = "=2.0.0-rc.10", features = ["download-binaries", "ndarray"] }
sotto-core = { package = "core", path = "../core" }

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "push"
harness = false
