[package]
name = "capture"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
sotto-core = { package = "core", path = "../core" }
cpal = "0.18.1"
crossbeam-queue = "0.3.13"
tokio.workspace = true

[dev-dependencies]
hound = "3.5.1"
libc = "0.2.189"
png = "0.18.1"
tempfile = "3.27.0"

[lints]
workspace = true
