[package]
name = "rag"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
fastembed = { version = "5.2.0", default-features = false, features = ["ort-download-binaries", "hf-hub-native-tls"] }
rusqlite = { version = "0.37.0", features = ["bundled", "serde_json"] }
serde.workspace = true
serde_json.workspace = true
sqlite-vec = "0.1.6"
sotto_core = { package = "core", path = "../core", features = ["serde"] }

[dev-dependencies]
tempfile = "3.20.0"
